// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which adapter captured (and can rehydrate) a node.
 */
export type AdapterKind = "chrome" | "terminal-app" | "vscode" | "cursor" | "generic";
