// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a query candidate represents. `Group` and `Assembled` candidates
 * carry an already-materialized workspace, so staging/rehydration treat
 * every kind identically.
 */
export type CandidateKind = "workspace" | "group" | "assembled";
