// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryCandidate } from "./QueryCandidate";

/**
 * Daemon -> UI responses. Progress may stream multiple times before Done.
 */
export type IpcResponse = { "type": "pong" } | { "type": "freeze-started", workspaceId: string, } | { "type": "query-results", candidates: Array<QueryCandidate>, } | { "type": "rehydrate-started" } | { "type": "progress", stage: string, detail: string, percent: number, } | { "type": "done", message: string, } | { "type": "error", code: string, message: string, };
