// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RehydrationPayload } from "./RehydrationPayload";

/**
 * UI -> daemon requests over the Unix domain socket.
 */
export type IpcRequest = { "type": "ping" } | { "type": "freeze" } | { "type": "query", text: string, limit: number, } | { "type": "rehydrate", payload: RehydrationPayload, };
