// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Points at one embeddable/rehydratable unit inside a workspace: a whole
 * window node, or (for Browser nodes) a single tab within it. Tab indices
 * are stable because nodes are immutable after capture — enrichment only
 * rewrites summaries/tags/labels, never nodes.
 */
export type ItemRef = { nodeId: string, 
/**
 * Some(i) = the i-th tab of a Browser node; None = the whole node.
 */
tabIndex: number | null, };
