// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserTab } from "./BrowserTab";
import type { TerminalTab } from "./TerminalTab";

/**
 * Adapter-specific state carried by a window node.
 */
export type NodePayload = { "kind": "browser", tabs: Array<BrowserTab>, activeTabIndex: number, } | { "kind": "terminal", tabs: Array<TerminalTab>, } | { "kind": "editor", folderPath: string, openFiles: Array<string>, } | { "kind": "generic" };
