// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterKind } from "./AdapterKind";

/**
 * Per-node dry-run of what rehydration would do, without launching anything.
 * Lets the UI warn about apps that vanished, windows that will be moved, and
 * tabs that will be skipped before the user commits.
 */
export type PreflightNode = { nodeId: string, appName: string, adapter: AdapterKind, 
/**
 * Whether the owning app appears installed (Spotlight-resolvable bundle id).
 */
installed: boolean, 
/**
 * Whether the captured window would be repositioned to fit an active
 * display (e.g. its original monitor is unplugged).
 */
geometryClamped: boolean, 
/**
 * Browser tabs captured vs. tabs that will be skipped for a disallowed URL
 * scheme; both zero for non-browser nodes.
 */
totalTabs: number, skippedTabs: number, 
/**
 * Human-readable notes for anything the user should know before committing.
 */
issues: Array<string>, };
