// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CandidateKind } from "./CandidateKind";
import type { WorkspaceState } from "./WorkspaceState";

/**
 * One semantic search hit; score is cosine similarity in [0, 1].
 */
export type QueryCandidate = { workspace: WorkspaceState, score: number, kind: CandidateKind, 
/**
 * For Group candidates: the snapshot this group was carved from.
 */
sourceWorkspaceId?: string | null, };
