// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceState } from "./WorkspaceState";

/**
 * What the user approved in the staging preview.
 */
export type RehydrationPayload = { workspace: WorkspaceState, excludedNodeIds: Array<string>, };
