// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterKind } from "./AdapterKind";
import type { NodePayload } from "./NodePayload";
import type { WindowGeometry } from "./WindowGeometry";

/**
 * One captured window: the unit the user can toggle in the staging preview.
 */
export type WindowNode = { nodeId: string, bundleId: string, appName: string, windowTitle: string, geometry: WindowGeometry, adapter: AdapterKind, payload: NodePayload, };
