// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geometry of a single window in global (screen) coordinates, in points.
 */
export type WindowGeometry = { x: number, y: number, width: number, height: number, };
