// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRef } from "./ItemRef";

/**
 * A semantic activity cluster within one workspace ("coding", "writing").
 * Membership is fixed at freeze time; only the label upgrades later.
 */
export type WorkspaceGroup = { 
/**
 * "g0", "g1", … ordered by member count descending.
 */
groupId: string, label: string, items: Array<ItemRef>, };
