// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowNode } from "./WindowNode";

/**
 * A frozen desktop: flat record, overwritten in place (no history).
 */
export type WorkspaceState = { workspaceId: string, 
/**
 * i64 on the Rust side, but the wire is JSON and the UI consumes it via
 * JSON.parse — so the TS type is number (unix ms fits in a double).
 */
capturedAtUnixMs: number, summary: string, tags: Array<string>, nodes: Array<WindowNode>, };
